source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "datalog-theme", "~> 0.10.0"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-paginate"
  gem "jekyll-include-cache"
end
