# frozen_string_literal: true

require_relative "test_helper"

class NotebookConversionTest < Minitest::Test
  NOTEBOOK_PAGE = "notebooks/sample-analysis/index.html"

  def setup
    @notebook_html = SiteBuilder.read(NOTEBOOK_PAGE)
  end

  def test_notebook_page_is_generated
    assert File.exist?(SiteBuilder.destination_path(NOTEBOOK_PAGE)),
           "Expected #{NOTEBOOK_PAGE} to be generated by the notebook converter"
  end

  def test_notebook_has_title_and_metadata
    assert_includes @notebook_html, "Notebook: Exploratory Data Snapshot",
                    "Notebook title should be rendered"
    assert_includes @notebook_html, "<meta name=\"keywords\" content=\"notebook\" />",
                    "Notebook metadata should include keywords"
  end

  def test_notebook_renders_code_cells
    assert_includes @notebook_html, "<code class=\"language-python\">import pandas as pd",
                    "Converted notebook should include code cell content"
    assert_match(/class="notebook-cell notebook-cell--input"/, @notebook_html,
                 "Notebook cells should include structural classes")
  end

  def test_notebook_includes_math_markup
    assert_includes @notebook_html, "$e^{i\\pi} + 1 = 0$",
                    "Inline math from the notebook should be preserved"
  end
end
