# frozen_string_literal: true

require_relative "test_helper"
require "nokogiri"

class NotebookConversionTest < Minitest::Test
  NOTEBOOK_PAGE = "notebooks/sample-analysis/index.html"

  def setup
    @notebook_html = SiteBuilder.read(NOTEBOOK_PAGE)
  end

  def test_notebook_page_is_generated
    assert File.exist?(SiteBuilder.destination_path(NOTEBOOK_PAGE)),
           "Expected #{NOTEBOOK_PAGE} to be generated by the notebook converter"
  end

  def test_notebook_has_title_and_metadata
    assert_includes @notebook_html, "Notebook: Exploratory Data Snapshot",
                    "Notebook title should be rendered"
    assert_includes @notebook_html, "<meta name=\"keywords\" content=\"notebook\" />",
                    "Notebook metadata should include keywords"
  end

  def test_notebook_renders_code_cells
    cell = Nokogiri::HTML5(@notebook_html).at_css(".notebook-cell--input pre.highlight code.language-python")

    refute_nil cell, "Converted notebook should include a Python code cell"
    assert cell.text.start_with?("import pandas as pd"), "The code cell should hold the notebook's source"
    assert_equal "import", cell.at_css("span.kn")&.text, "Rouge should highlight the cell as the site builds"
    assert_match(/class="notebook-cell notebook-cell--input"/, @notebook_html,
                 "Notebook cells should include structural classes")
  end

  def test_notebook_includes_math_markup
    assert_includes @notebook_html, "$e^{i\\pi} + 1 = 0$",
                    "Inline math from the notebook should be preserved"
  end
end
