#!/usr/bin/env ruby
# frozen_string_literal: true

root = File.join(__dir__, "..")
head = File.read(File.join(root, "_includes", "head.html"))
visualizations = File.read(File.join(root, "assets", "js", "visualizations.js"))
post_layout = File.read(File.join(root, "_layouts", "post.html"))
research_layout = File.read(File.join(root, "_layouts", "research.html"))

# The CSP meta tag is generated by _includes/csp-meta.html, pulled in by head.html.
csp_include = File.read(File.join(root, "_includes", "csp-meta.html"))
unless head.include?("include csp-meta.html") && csp_include.include?("Content-Security-Policy")
  raise "Head include missing CSP declaration"
end

%w[sandbox allow-scripts allow-same-origin].each do |token|
  raise "Visualization embeds missing #{token} enforcement" unless visualizations.include?(token)
end

unless post_layout.include?("rel=\"noopener noreferrer\"") && research_layout.include?("rel=\"noopener noreferrer\"")
  raise "External links must use rel=\"noopener noreferrer\" for security"
end

puts "Security hardening verified for CSP, sandboxed visualizations, and safe external links."
